# Generated by Django 4.2 on 2023-07-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers_hub', '0004_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
